export const addtodo = "ADD_TODO_ITEM"
export const completetodo = "COMPLETED_TODO_ITEM"
export const deletetodo = "DELETE_TODO_ITEM"
export const checkboxtodo = "CHECK_TODO_ITEM"
export const clearCompletedTodo = "CLEAR_COMPLETED_TODO"